# Generated by Django 3.2 on 2022-03-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LSCSession',
        ),
    ]
